version: '3.1'
services:
  moe-shop-frontend:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: moe-shop-frontend:0.0.1
    container_name: moe-shop-frontend-container
    ports:
      - "80:80"
    env_file:
      - .env
