version: '3.1'
services:
  fe-moe:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: fe-moe:1.0.0
    container_name: fe-moe-container
    ports:
      - "1004:1004"
    env_file:
      - .env
