version: '3.1'
services:
  moe-shop-fontend:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: moe-shop-fontend:0.0.1
    container_name: moe-shop-fontend-container
    ports:
      - "80:80"
    env_file:
      - .env
