# Author: Nong Hoang Vu || JavaTech
# Facebook:https://facebook.com/NongHoangVu04
# Github: https://github.com/JavaTech04
# Youtube: https://www.youtube.com/@javatech04/?sub_confirmation=1 13.230.106.99
server:
  port: 2004
api:
  version: v2
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3307/sd79_db_moe}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123}
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  data:
    redis:
      host: ${HOST:localhost}
      port: 6379
  config:
    activate:
      on-profile: prd
jwt:
  key: PRODUCT_SD79NHV$2a$12$wvYek6dEmfHd3QOhnY2BVe8LbTGQa7bo2mda3FrHez80ToFEEh5u.
  expiryMinute: 1000
  expiryDay: 3
  secretKey: b0238cff00a72de79bebabb5b5d6a777ff4b5f0401e6518ea03d48262f4bd818
  refreshKey: 9106746cb1d349b31174dda29c2729d3448d9b8a57418cc1833c8478f0763980
  otherKey: 9106746cb1d349b31174dda29c2729d3448d9b8a57418cc1833c8478f0763980s
openapi:
  service:
    api-docs: api-moe-shop
    title: ${API_TITLE:DUMMY_VALUE_API}
    version: ${api.version}
    description: description
    server: http://${HOST:localhost}:2004
    serverName: JavaTech
    license: Apache 2.0
    license-url: https://facebook.com/NongHoangVu04
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:DUMMY_VALUE}
  api-secret: ${CLOUDINARY_API_SECRET:DUMMY_VALUE}
  api-key: ${CLOUDINARY_API_KEY:DUMMY_VALUE}