# Author: Nong Hoang Vu || JavaTech
# Facebook:https://facebook.com/NongHoangVu04
# Github: https://github.com/JavaTech04
# Youtube: https://www.youtube.com/@javatech04/?sub_confirmation=1
spring:
  application:
    name: BE-MOE
  main:
    banner-mode: console
  banner:
    location: static/banner.txt
  profiles:
    active: @spring.profiles.active@
  authentication:
    username: sysadmin
    password: sd79
payment:
  vnPay:
    url: ${VNPAY_URL}
    tmnCode: ${VNPAY_TMNCODE}
    secretKey: ${VNPAY_SECRET_KEY}
    returnUrl: http://localhost:1004/
    version: 2.1.0
    command: pay
    orderType: OTHER
logging:
  level:
    root: INFO
    web: INFO
    org.springframework: INFO
    org.apache: ERROR
    kafka: ERROR
