# Author: Nong Hoang Vu || JavaTech
# Facebook:https://facebook.com/NongHoangVu04
# Github: https://github.com/JavaTech04
# Youtube: https://www.youtube.com/@javatech04/?sub_confirmation=1
server:
  port: 2004
api:
  version: v2
spring:
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  config:
    activate:
      on-profile: prd
jwt:
  key: ${JWT_KEY}
  expiryMinute: ${JWT_EXPIRY_MINUTE}
  expiryDay: ${JWT_EXPIRY_DAY}
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}
  otherKey: ${JWT_OTHER_KEY}
openapi:
  service:
    api-docs: ${API_DOCUMENT:DUMMY_DOCS}
    title: ${API_DOCUMENT_TITLE:DUMMY_VALUE_API}
    version: ${api.version}
    description: ${API_DOCUMENT_DESCRIPTION:DUMMY_DESCRIPTION}
    server: ${API_DOCUMENT_SERVER:http://localhost:${server.port}}
    serverName: ${API_DOCUMENT_SERVERNAME:DUMMY_SERVER_NAME}
    license: Apache 2.0
    license-url: ${API_DOCUMENT_LICENSE_URL:NOT_FOUNT}
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:DUMMY_VALUE}
  api-secret: ${CLOUDINARY_API_SECRET:DUMMY_VALUE}
  api-key: ${CLOUDINARY_API_KEY:DUMMY_VALUE}