# Author: Nong Hoang Vu || JavaTech
# Facebook:https://facebook.com/NongHoangVu04
# Github: https://github.com/JavaTech04
# Youtube: https://www.youtube.com/@javatech04/?sub_confirmation=1
# dnvsezlqx Q_CCV07_nZjRJbzwyK8_23WK3KQ 734814185473685
# ROLE: LEADER
server:
  port: 2004
api:
  version: v2
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sd79_db_moe
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
  config:
    activate:
      on-profile: nhv
jwt:
  key: LEADER_SD79NHV$2a$12$wvYek6dEmfHd3QOhnY2BVe8LbTGQa7bo2mda3FrHez80ToFEEh5u.
  expiryMinute: 1000
  expiryDay: 3
  secretKey: 48a5d6ea1af7eddbb926ccab5c50296c4b88f4a673f50246c8d25b0b3ea23537
  refreshKey: bf2d8f6e53e5c1b5575e25038761f679b691912e1d2e00c7ca9ed1ea16692f50
  otherKey: da429bf1a3a0a80bf60df05085b61cc0fd40a75bca1149fa0f90e18d27973cbe
openapi:
  service:
    api-docs: api-moe-shop
    title: MOE-SHOP-API
    version: ${api.version}
    description: description
    server: http://localhost:2004
    serverName: JavaTech
    license: Apache 2.0
    license-url: https://facebook.com/NongHoangVu04
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:DUMMY_VALUE}
  api-secret: ${CLOUDINARY_API_SECRET:DUMMY_VALUE}
  api-key: ${CLOUDINARY_API_KEY:DUMMY_VALUE}